### ISSUE TITLE
add topic jekyll-theme for support in GitHub pages

### ISSUE THREAD

**Issue by julou** [awochna/jekyll-skeleton#12]
now that GitHub pages support "all open source Jekyll themes hosted on GitHub" (aka repo with the topic jekyll-theme), could you please add this topic or edit your current jekyll-themes to jekyll-theme?
Thank you very much!

Best,
Thomas

**Comment by julou** [comment]
btw I dont know how GitHub pages handle cases where several repos with this topic have the same name…
https://github.com/topics/jekyll-theme?utf8=✓&q=jekyll-skeleton

**Comment by awochna** [comment]
That's a great question and thank you for bringing it to my attention, @julou ! I just read the new feature for Github pages myself and saw this issue in my notifications. I'm glad you're making use of this theme.

**Comment by awochna** [comment]
This has been changed!

**Comment by julou** [comment]
thx!
somehow it still doesn't work :( maybe related to the name conflict?!
NB: I've not tried other user-contributed themes though…
